version: 2.1

jobs:
  postman-tests:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout

      - run:
          name: Install Newman
          command: npm install -g newman

      - run:
          name: Run ClickUp Tasks API collection
          command: |
            newman run "postman/ClickUp Tasks API Course Project.postman_collection.json" \
              -e "postman/ClickUp_Tasks_Env.postman_environment.json" \
              --env-var "base_url=https://api.clickup.com/api/v2" \
              --env-var "token=${CLICKUP_TOKEN}" \
              --env-var "list_id=901219175349" \
              --env-var "invalid_task_id=invalid_task_id_12345"

workflows:
  test:
    jobs:
      - postman-tests
